package utils;

public enum Fields {
    USER_NAME,
    PASSWORD,
    EMAIL,
    LOGIN_BUTTON,
    BARRE_ENROLL,
    BARRE_WAIT,
    PILATES_ENROLL,
    PILATES_WAIT,
    PILBARRE_ENROLL,
    PILBARRE_WAIT,
    YOGAILATES_ENROLL,
    YOGAILATES_WAIT,
    SUBMIT_ENROLL_BUTTON,
    SUBMIT_WAIT_BUTTON,
    ENROLL_CONFIRMATION,
    WAIT_LIST_CONFIRMATION
}
